spring:
  application:
    name: gadjetStore
  datasource:
    url: jdbc:postgresql://localhost:5432/java17
    username: postgres
    password: busubaha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8085

security:
  secret:
    key: "Java17Backand"
