spring:
  application:
    name: gadjetStore
  datasource:
    url: jdbc:postgresql://localhost:5432/java17
    username: postgres
    password: busubaha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

security:
  secret:
    key: "Java17Backand"
